# -*- coding: utf-8 -*-
"""Milestone4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dRKH2VL7qbOhCF7v_kfr9AYK50nr_Pmo
"""

import pandas as pd
df=pd.read_csv("cleaned_power_consumption.csv")
df.head()

df['Datetime'] = pd.to_datetime(df['Datetime'])
df = df.sort_values('Datetime')

df.columns

y=df['Global_active_power']

X = df[['Hour', 'Day', 'DayOfWeek', 'Month',
        'IsWeekend',
        'Lag_1', 'Lag_24',
        'RollingMean_6', 'RollingMean_24']]

from sklearn.linear_model import LinearRegression

split = int(len(df)*0.8)

X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

model = LinearRegression()
model.fit(X_train, y_train)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

df['Datetime'] = pd.to_datetime(df['Datetime'])

df['Hour'] = df['Datetime'].dt.hour
df['Day'] = df['Datetime'].dt.day
df['Week'] = df['Datetime'].dt.isocalendar().week
df['DayOfWeek'] = df['Datetime'].dt.day_name()

hourly_avg = df.groupby('Hour')['Global_active_power'].mean()

plt.figure(figsize=(10,5))
hourly_avg.plot(marker='o')
plt.title("Average Hourly Energy Consumption")
plt.xlabel("Hour of Day")
plt.ylabel("Average Global Active Power")
plt.grid(True)
plt.show()

daily_avg = df.groupby('Day')['Global_active_power'].mean()

plt.figure(figsize=(10,5))
daily_avg.plot(marker='o', color='orange')
plt.title("Average Daily Energy Consumption")
plt.xlabel("Day of Month")
plt.ylabel("Average Global Active Power")
plt.grid(True)
plt.show()

weekly_avg = df.groupby('Week')['Global_active_power'].mean()

plt.figure(figsize=(10,5))
weekly_avg.plot(marker='o', color='green')
plt.title("Average Weekly Energy Consumption")
plt.xlabel("Week Number")
plt.ylabel("Average Global Active Power")
plt.grid(True)
plt.show()

dow_avg = df.groupby('DayOfWeek')['Global_active_power'].mean()
dow_avg = dow_avg.reindex(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'])

plt.figure(figsize=(10,5))
dow_avg.plot(kind='bar', color='purple')
plt.title("Energy Usage by Day of Week")
plt.xlabel("Day")
plt.ylabel("Average Global Active Power")
plt.show()

peak_hour = hourly_avg.idxmax()
peak_value = hourly_avg.max()

print("Peak Usage Hour:", peak_hour)
print("Highest Average Consumption:", peak_value)

def energy_suggestions(df):
    suggestions = []

    peak_hour = df.groupby('Hour')['Global_active_power'].mean().idxmax()

    if peak_hour in range(18, 23):
        suggestions.append("High consumption in evening (6PM–10PM). Reduce AC/heater usage.")

    if df['IsWeekend'].mean() > 0.5:
        suggestions.append("Weekend usage is high. Limit heavy appliances usage.")

    if df['Global_active_power'].mean() > 1.5:
        suggestions.append("Overall consumption is high. Consider energy-efficient appliances.")

    return suggestions

tips = energy_suggestions(df)

print("Smart Energy Saving Suggestions:")
for tip in tips:
    print("-", tip)

print("===== DASHBOARD SUMMARY =====")
print("Average Consumption:", round(df['Global_active_power'].mean(),2))
print("Maximum Consumption:", df['Global_active_power'].max())
print("Minimum Consumption:", df['Global_active_power'].min())
print("Peak Hour:", peak_hour)

from google.colab import files
import pandas as pd

# Upload your CSV file
uploaded = files.upload()
# Make sure you select 'cleaned_power_consumption.csv'

# Read the dataset
df = pd.read_csv("cleaned_power_consumption.csv")
df['Datetime'] = pd.to_datetime(df['Datetime'])
df['Hour'] = df['Datetime'].dt.hour
df['Day'] = df['Datetime'].dt.day
df['Week'] = df['Datetime'].dt.isocalendar().week
df['DayOfWeek'] = df['Datetime'].dt.day_name()
df['IsWeekend'] = df['DayOfWeek'].isin(['Saturday','Sunday']).astype(int)

print("Dataset loaded successfully! ✅")
df.head()

!pip install flask pyngrok

!ngrok authtoken 39ks7HipobRDk6hPKeGqEbw1SRz_6Z5UcdckSk8864yYxresT

pip freeze > requirements.txt

with open("Procfile", "w") as f:
    f.write("web: gunicorn app:app")

!ls

from google.colab import files

files.download("Procfile")
files.download("requirements.txt")
files.download("cleaned_power_consumption (1).csv")   # or your correct csv name

files.download("app.py")

df = pd.read_csv("small_dataset.csv")

import pandas as pd

# Load your big dataset
df = pd.read_csv("cleaned_power_consumption (1).csv")

# Take first 40,000 rows (safe size under 25MB usually)
df_small = df.head(40000)

# Save as new CSV
df_small.to_csv("small_dataset.csv", index=False)

print("Small dataset created successfully!")

from google.colab import files
files.download("small_dataset.csv")

from flask import Flask, render_template_string, request
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import base64
from io import BytesIO

app = Flask(__name__)

# -----------------------------
# LOAD DATA (small dataset for deployment)
# -----------------------------
df = pd.read_csv('small_dataset.csv')  # <- Make sure this file is in your repo

df['Datetime'] = pd.to_datetime(df['Datetime'], dayfirst=True)
df.set_index('Datetime', inplace=True)

device_cols = ['Sub_metering_1','Sub_metering_2','Sub_metering_3']

for col in device_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.fillna(method='ffill', inplace=True)

# -----------------------------
# HELPER FUNCTIONS
# -----------------------------
def plot_to_base64(fig):
    buffer = BytesIO()
    fig.savefig(buffer, format='png', bbox_inches='tight')
    buffer.seek(0)
    image = base64.b64encode(buffer.getvalue()).decode('utf-8')
    buffer.close()
    return image

def simple_forecast(series, steps=7):
    last_value = series.iloc[-1]
    trend = series.diff().mean()
    return [last_value + trend*i for i in range(1, steps+1)]

def generate_alerts(grouped):
    alerts = []
    suggestions = []

    avg_usage = grouped.mean().mean()

    if avg_usage > 20000:
        alerts.append("⚠️ High energy usage detected!")
        suggestions.append("Reduce usage of high-power appliances during peak hours.")

    highest_device = grouped.mean().idxmax()
    suggestions.append(f"Highest consumption from {highest_device}. Consider optimizing it.")

    return alerts, suggestions

# -----------------------------
# ROUTE
# -----------------------------
@app.route('/', methods=['GET','POST'])
def index():
    period = request.form.get("period", "Daily")

    if period == "Daily":
        grouped = df[device_cols].resample('D').sum()
    elif period == "Weekly":
        grouped = df[device_cols].resample('W').sum()
    elif period == "Yearly":
        grouped = df[device_cols].resample('Y').sum()

    grouped = grouped.tail(60)

    fig1, ax1 = plt.subplots(figsize=(15,5))
    grouped.plot(ax=ax1, linewidth=2)
    ax1.set_title(f"{period} Device Consumption", fontsize=15)
    ax1.set_xlabel("Time", fontsize=12)
    ax1.set_ylabel("Energy (Wh)", fontsize=12)
    plt.xticks(rotation=45)
    plt.tight_layout()
    device_graph = plot_to_base64(fig1)
    plt.close(fig1)

    total_series = grouped.sum(axis=1)
    forecast_values = simple_forecast(total_series, 7)

    fig2, ax2 = plt.subplots(figsize=(15,5))
    ax2.plot(total_series.values, linewidth=2, label="Actual")
    ax2.plot(range(len(total_series), len(total_series)+7),
             forecast_values, linestyle='--', linewidth=2, label="Predicted")
    ax2.set_title("Future Energy Prediction (Next 7 Periods)", fontsize=15)
    ax2.set_xlabel("Time", fontsize=12)
    ax2.set_ylabel("Energy (Wh)", fontsize=12)
    ax2.legend()
    plt.tight_layout()
    prediction_graph = plot_to_base64(fig2)
    plt.close(fig2)

    alerts, suggestions = generate_alerts(grouped)

    html = f"""
    <h1 style='text-align:center;'>Smart Energy Dashboard</h1>

    <form method="POST" style="margin-bottom:20px;">
        <label>Select Period:</label>
        <select name="period">
            <option value="Daily">Daily</option>
            <option value="Weekly">Weekly</option>
            <option value="Yearly">Yearly</option>
        </select>
        <button type="submit">Show</button>
    </form>

    <h2>📊 Device Consumption</h2>
    <img src="data:image/png;base64,{device_graph}" />

    <h2>🔮 Future Prediction</h2>
    <img src="data:image/png;base64,{prediction_graph}" />

    <h2>⚠️ Alerts</h2>
    <ul>
    {''.join(f'<li style="color:red;">{a}</li>' for a in alerts) if alerts else '<li>No Alerts</li>'}
    </ul>

    <h2>💡 Recommendations</h2>
    <ul>
    {''.join(f'<li>{s}</li>' for s in suggestions)}
    </ul>
    """

    return render_template_string(html)

# -----------------------------
# RENDER-READY START
# -----------------------------
if __name__ == "__main__":
    import os
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)