# -*- coding: utf-8 -*-
"""Milestone4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dRKH2VL7qbOhCF7v_kfr9AYK50nr_Pmo
"""

from flask import Flask, render_template_string, request
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import base64
from io import BytesIO

app = Flask(__name__)

# -----------------------------
# LOAD DATA
# -----------------------------
df = pd.read_csv('small_dataset.csv')

df['Datetime'] = pd.to_datetime(df['Datetime'], dayfirst=True)
df.set_index('Datetime', inplace=True)

device_cols = ['Sub_metering_1','Sub_metering_2','Sub_metering_3']

for col in device_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.fillna(method='ffill', inplace=True)

# -----------------------------
# HELPER FUNCTIONS
# -----------------------------
def plot_to_base64(fig):
    buffer = BytesIO()
    fig.savefig(buffer, format='png', bbox_inches='tight')
    buffer.seek(0)
    image = base64.b64encode(buffer.getvalue()).decode('utf-8')
    buffer.close()
    return image

def simple_forecast(series, steps=7):
    last_value = series.iloc[-1]
    trend = series.diff().mean()
    return [last_value + trend*i for i in range(1, steps+1)]

def generate_alerts(grouped):
    alerts = []
    suggestions = []

    avg_usage = grouped.mean().mean()

    if avg_usage > 20000:
        alerts.append("⚠️ High energy usage detected!")
        suggestions.append("Reduce usage of high-power appliances during peak hours.")

    highest_device = grouped.mean().idxmax()
    suggestions.append(f"Highest consumption from {highest_device}. Consider optimizing it.")

    return alerts, suggestions

# -----------------------------
# ROUTE
# -----------------------------
@app.route('/', methods=['GET','POST'])
def index():
    period = request.form.get("period", "Daily")

    if period == "Daily":
        grouped = df[device_cols].resample('D').sum()
    elif period == "Weekly":
        grouped = df[device_cols].resample('W').sum()
    elif period == "Yearly":
        grouped = df[device_cols].resample('Y').sum()

    grouped = grouped.tail(60)

    # Graph 1
    fig1, ax1 = plt.subplots(figsize=(15,5))
    grouped.plot(ax=ax1, linewidth=2)
    ax1.set_title(f"{period} Device Consumption")
    plt.xticks(rotation=45)
    plt.tight_layout()
    device_graph = plot_to_base64(fig1)
    plt.close(fig1)

    # Graph 2 (prediction)
    total_series = grouped.sum(axis=1)
    forecast_values = simple_forecast(total_series, 7)

    fig2, ax2 = plt.subplots(figsize=(15,5))
    ax2.plot(total_series.values, label="Actual")
    ax2.plot(range(len(total_series), len(total_series)+7),
             forecast_values, linestyle='--', label="Predicted")
    ax2.legend()
    plt.tight_layout()
    prediction_graph = plot_to_base64(fig2)
    plt.close(fig2)

    alerts, suggestions = generate_alerts(grouped)

    html = f"""
    <h1 style='text-align:center;'>Smart Energy Dashboard</h1>

    <form method="POST">
        <select name="period">
            <option value="Daily">Daily</option>
            <option value="Weekly">Weekly</option>
            <option value="Yearly">Yearly</option>
        </select>
        <button type="submit">Show</button>
    </form>

    <h2>Device Consumption</h2>
    <img src="data:image/png;base64,{device_graph}" />

    <h2>Future Prediction</h2>
    <img src="data:image/png;base64,{prediction_graph}" />

    <h2>Alerts</h2>
    <ul>
    {''.join(f'<li>{a}</li>' for a in alerts) if alerts else '<li>No Alerts</li>'}
    </ul>

    <h2>Recommendations</h2>
    <ul>
    {''.join(f'<li>{s}</li>' for s in suggestions)}
    </ul>
    """

    return render_template_string(html)

# -----------------------------
# START
# -----------------------------
if __name__ == "__main__":
    import os
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
